#!/usr/bin/env python3
"""Generate Ryu's 128-bit lookup tables for the Nim port of d2s.

The two tables that Ulf Adams' reference `d2s_full_table.h` ships verbatim are
derived here from exact big-integer arithmetic instead of being transcribed, so
they can be regenerated and audited.  Each entry is a 128-bit number stored as
two uint64 limbs [low, high].

Definitions (DOUBLE_POW5_BITCOUNT == DOUBLE_POW5_INV_BITCOUNT == 125):

  pow5bits(e)              = ((e * 1217359) >> 19) + 1     # == floor(e*log2 5)+1
  DOUBLE_POW5_SPLIT[i]     = 5^i  scaled to 125 bits
                           = 5^i >> (pow5bits(i) - 125)    # left-shift if neg
  DOUBLE_POW5_INV_SPLIT[i] = (2^(pow5bits(i) - 1 + 125) // 5^i) + 1

Anchors checked below against the published constants:
  POW5_SPLIT[0]     = {0, 1152921504606846976}      (= 2^60)
  POW5_SPLIT[1]     = {0, 1441151880758558720}      (= 5 * 2^58)
  POW5_INV_SPLIT[0] = {1, 2305843009213693952}      (= 2^61 + 1)
"""

POW5_SPLIT_SIZE = 326       # i = 0 .. 325
POW5_INV_SPLIT_SIZE = 342   # i = 0 .. 341
BITCOUNT = 125
MASK64 = (1 << 64) - 1


def pow5bits(e: int) -> int:
    return ((e * 1217359) >> 19) + 1


def pow5_split(i: int) -> int:
    pow5 = 5 ** i
    shift = pow5bits(i) - BITCOUNT
    return pow5 >> shift if shift >= 0 else pow5 << (-shift)


def pow5_inv_split(i: int) -> int:
    j = pow5bits(i) - 1 + BITCOUNT
    return ((1 << j) // (5 ** i)) + 1


def limbs(v: int) -> tuple[int, int]:
    return v & MASK64, (v >> 64) & MASK64


def check() -> None:
    assert limbs(pow5_split(0)) == (0, 1152921504606846976)
    assert limbs(pow5_split(1)) == (0, 1441151880758558720)
    assert limbs(pow5_inv_split(0)) == (1, 2305843009213693952)
    # every entry must fit in 128 bits
    for i in range(POW5_SPLIT_SIZE):
        assert pow5_split(i) >> 128 == 0, i
    for i in range(POW5_INV_SPLIT_SIZE):
        assert pow5_inv_split(i) >> 128 == 0, i


def emit(name: str, n: int, fn) -> str:
    lines = [f"const {name}*: array[{n}, array[2, uint64]] = ["]
    for i in range(n):
        lo, hi = limbs(fn(i))
        lines.append(f"  [{lo}'u64, {hi}'u64],")
    lines.append("]")
    return "\n".join(lines)


def main() -> None:
    check()
    out = [
        "## Ryu 128-bit power-of-five lookup tables.",
        "## GENERATED by tools/gen_ryu_tables.py -- do not edit by hand.",
        "## Each entry is a 128-bit value stored as [low64, high64].",
        "",
        "const DOUBLE_POW5_BITCOUNT* = 125",
        "const DOUBLE_POW5_INV_BITCOUNT* = 125",
        "",
        emit("DOUBLE_POW5_SPLIT", POW5_SPLIT_SIZE, pow5_split),
        "",
        emit("DOUBLE_POW5_INV_SPLIT", POW5_INV_SPLIT_SIZE, pow5_inv_split),
        "",
    ]
    import os
    dest = os.path.join(os.path.dirname(__file__), "..", "nim", "src", "ryu_tables.nim")
    with open(dest, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.normpath(dest)}")


if __name__ == "__main__":
    main()
