#!/usr/bin/env python3
"""Generate the shared JSON5 identifier classification tables for both the Nim
and Python parsers.

JSON5 unquoted keys follow the ECMAScript IdentifierName grammar, which is
defined by Unicode general categories. Those categories differ between Python's
bundled `unicodedata` and Nim's `std/unicode`, so relying on each language's own
database would break byte-parity. Instead we compute the code-point ranges ONCE
here and embed the identical table in both implementations (same idea as the Ryu
tables: one generator, two emitted files).

  IdentifierStart    = Lu Ll Lt Lm Lo Nl                      (+ ASCII _ $)
  IdentifierContinue = IdentifierStart + Mn Mc Nd Pc + ZWNJ/ZWJ   (+ ASCII _ $)

ASCII (< 0x80) is handled inline by the parsers, so the tables cover only
non-ASCII code points (>= 0x80), keeping them compact.
"""
import os
import unicodedata

START_CATS = {"Lu", "Ll", "Lt", "Lm", "Lo", "Nl"}
CONT_EXTRA = {"Mn", "Mc", "Nd", "Pc"}
ZWNJ, ZWJ = 0x200C, 0x200D
MAXCP = 0x110000


def build_ranges(predicate) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    lo = None
    for cp in range(0x80, MAXCP):
        if predicate(cp):
            if lo is None:
                lo = cp
        elif lo is not None:
            ranges.append((lo, cp - 1))
            lo = None
    if lo is not None:
        ranges.append((lo, MAXCP - 1))
    return ranges


def is_start(cp: int) -> bool:
    return unicodedata.category(chr(cp)) in START_CATS


def is_continue(cp: int) -> bool:
    if cp in (ZWNJ, ZWJ):
        return True
    return unicodedata.category(chr(cp)) in (START_CATS | CONT_EXTRA)


def emit_nim(start: list, cont: list) -> str:
    def arr(name: str, rs: list) -> str:
        body = ",\n  ".join(f"[{lo}'u32, {hi}'u32]" for lo, hi in rs)
        return f"const {name}*: array[{len(rs)}, array[2, uint32]] = [\n  {body}]"
    return f"""## JSON5 identifier code-point ranges (non-ASCII), shared with Python.
## GENERATED by tools/gen_id_tables.py from Unicode {unicodedata.unidata_version}.
## Do not edit by hand. Each entry is an inclusive [lo, hi] code-point range.

{arr("ID_START", start)}

{arr("ID_CONTINUE", cont)}

proc inRanges(cp: uint32, rs: openArray[array[2, uint32]]): bool =
  var lo = 0
  var hi = rs.len - 1
  while lo <= hi:
    let mid = (lo + hi) div 2
    if cp < rs[mid][0]: hi = mid - 1
    elif cp > rs[mid][1]: lo = mid + 1
    else: return true
  false

proc isJson5IdStart*(cp: uint32): bool = inRanges(cp, ID_START)
proc isJson5IdContinue*(cp: uint32): bool = inRanges(cp, ID_CONTINUE)
"""


def emit_python(start: list, cont: list) -> str:
    def arr(name: str, rs: list) -> str:
        body = ", ".join(f"({lo},{hi})" for lo, hi in rs)
        return f"{name} = ({body},)"
    return f'''"""JSON5 identifier code-point ranges (non-ASCII), shared with Nim.

GENERATED by tools/gen_id_tables.py from Unicode {unicodedata.unidata_version}.
Do not edit by hand. Each entry is an inclusive (lo, hi) code-point range.
"""
from bisect import bisect_right

{arr("ID_START", start)}

{arr("ID_CONTINUE", cont)}


def _in_ranges(cp: int, ranges: tuple[tuple[int, int], ...]) -> bool:
    i = bisect_right(ranges, (cp, cp + 1))
    if i and ranges[i - 1][0] <= cp <= ranges[i - 1][1]:
        return True
    return i < len(ranges) and ranges[i][0] <= cp <= ranges[i][1]


def is_json5_id_start(cp: int) -> bool:
    return _in_ranges(cp, ID_START)


def is_json5_id_continue(cp: int) -> bool:
    return _in_ranges(cp, ID_CONTINUE)
'''


def main() -> None:
    start = build_ranges(is_start)
    cont = build_ranges(is_continue)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    nim_path = os.path.join(root, "nim", "src", "json5_ident.nim")
    py_path = os.path.join(root, "python", "jsoncanon", "_json5_ident.py")
    with open(nim_path, "w") as f:
        f.write(emit_nim(start, cont))
    with open(py_path, "w") as f:
        f.write(emit_python(start, cont))
    print(f"Unicode {unicodedata.unidata_version}: "
          f"{len(start)} start ranges, {len(cont)} continue ranges")
    print(f"wrote {os.path.relpath(nim_path, root)} and {os.path.relpath(py_path, root)}")


if __name__ == "__main__":
    main()
